package org.example;// Generated by Selenium IDE
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class CreateNewNoteTest extends TestBase {


  @Test
  public void createNote() throws InterruptedException {
    LoginData user = new LoginData("9047691056", "nata091074");
    manager.goTo().OpenHomePage();
    manager.login().InputLogin(user);
    manager.login().InputPassword(user);
    manager.noteHelper().createNote();

   }


}
